config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  resources :events
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


	post '/g_invitation', to: 'invitations#generate'



	get '/show', to: 'shows#index'

	post '/shows', to: 'shows#confirm'

	post '/showsc', to: 'shows#reject'

	get '/touchdown', to: 'touchdowns#index'


	root to: "events#index"

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :title, optional: true
  belongs_to :firm, optional: true
  belongs_to :position, optional: true

  validates :names, presence: true
  validates :last_names, presence: true
  validates :email, presence: true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:names, :last_names, :group_id, :title_id, :firm_id, :position_id, :email)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_id %>
    <%= f.collection_select :title_id, Title.all , :id, :name, {prompt: 'Seleccione Titulo'}%>
  </div>

  <div class="field">
    <%= f.label :names %>
    <%= f.text_field :names %>
  </div>

  <div class="field">
    <%= f.label :last_names %>
    <%= f.text_field :last_names %>
  </div>

  <div class="field">
    <%= f.label :group_id %>
    <%= f.collection_select :group_id, Group.all , :id, :name, {prompt: 'Seleccione Grupo'}%>
  </div>

  

  <div class="field">
    <%= f.label :firm_id %>
    <%= f.collection_select :firm_id, Firm.all , :id, :name, {prompt: 'Seleccione Empresa'}%>
  </div>

  <div class="field">
    <%= f.label :position_id %>
    <%= f.collection_select :position_id, Position.all , :id, :name, {prompt: 'Seleccione Cargo'}%>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Names</th>
      <th>Last names</th>
      <th>Group</th>
      <th>Title</th>
      <th>Firm</th>
      <th>Position</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.names %></td>
        <td><%= person.last_names %></td>
        <td><%= person.group %></td>
        <td><%= person.title %></td>
        <td><%= person.firm %></td>
        <td><%= person.position %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Names:</strong>
  <%= @person.names %>
</p>

<p>
  <strong>Last names:</strong>
  <%= @person.last_names %>
</p>

<p>
  <strong>Group:</strong>
  <%= @person.group %>
</p>

<p>
  <strong>Title:</strong>
  <%= @person.title %>
</p>

<p>
  <strong>Firm:</strong>
  <%= @person.firm %>
</p>

<p>
  <strong>Position:</strong>
  <%= @person.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>